### ISSUE TITLE
add citation

### ISSUE THREAD

**Issue by tischi** [platybrowser/mmb-fiji#10]

**Comment by constantinpape** [comment]
I added a short paragraph that asks users to cite the paper if they use MMB:
https://github.com/platybrowser/mmb-fiji/blob/master/README.md#citation

We might consider adding something on important software for MMB too:
Fiji, BDV, ?

**Comment by tischi** [comment]
> We might consider adding something on important software for MMB too:
Fiji, BDV, ?

Good question. I am not sure, since we cite them already in our paper, thus maybe not really appropriate? I guess one cannot ask people to cite everything...

**Comment by constantinpape** [comment]
We have a link to the paper in the rdme now.
