### ISSUE TITLE
PlatyBrowser doesn't open  

### ISSUE THREAD

**Issue by vzinche** [platybrowser/mmb-fiji#1032]
![Screenshot from 2023-05-04 15-08-20](https://user-images.githubusercontent.com/32451366/236214053-15ac29d7-3810-4a0e-a5e9-83dd947f6a9e.png)

**Comment by tischi** [comment]
@vzinche can you please update MoBIE-beta and try again?

**Comment by vzinche** [comment]
Works now, thanks :+1:
