### ISSUE TITLE
Select active label source

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/mmb-fiji#4]
In order to deal with multiple segmentations / label sources in the platy browser,
it would be very helpful to enable selecting the active label source.

For the active label source, one can highlight selected cells and use the 3d view etc.

What we would need to figure out is how this relates to the attribute tables;
probably we would need to specify which table is connected to which label source and then select the proper table for the active label source.

**Comment by tischi** [comment]
Could make one folder where for each label image there is exactly one table?
Would be nice if all of them contained at least the centre-of-mass object coordinates.
Other versions of the tables could be in a different folder.

**Comment by constantinpape** [comment]
> Could make one folder where for each label image there is exactly one table?

Yes, that would be an easy solution.

> Would be nice if all of them contained at least the centre-of-mass object coordinates.

Yes. We might need to generalize this a bit though. E.g. for skeletons the actual COM will not make much sense and we would instead need "the most central point". Or maybe a terminal point.

**Comment by tischi** [comment]
> Yes. We might need to generalize this a bit though. E.g. for skeletons the actual COM will not make much sense and we would instead need "the most central point". Or maybe a terminal point.

Very good point! 

What about, e.g., `anchor_x`,`anchor_y`,`anchor_z` for the coordinates that will be moved to when the user clicks on a row in the table?

I would use `anchor` instead of `central`, because, e.g., for neuron tracing tracks you may want to move to the start rather than the center.

**Comment by constantinpape** [comment]
Yes, I think `anchor` is a good choice.

**Comment by tischi** [comment]
ok! could you do all of this for two of our segments such that I have something to play with?

**Comment by constantinpape** [comment]
Yes, will let you know when it's there.

**Comment by constantinpape** [comment]
I made a new sub-folder called `tables`. In there, you can find the tables for the latest cell segmentation and nucleus segmentation (same filenames just .h5 / .xml replaced with .csv).
The tables contain the following columns:
```
label_id, anchor_x, anchor_y, anchor_z, bb_min_x, ..., bb_max_x, ...
```
The `bb` columns contain the bounding box coordinates (I thought that might be useful as well, because you need this for the 3d rendering).

**Comment by tischi** [comment]
Great! I will work on it during the next days...

**Comment by tischi** [comment]
I am making good progress!

Can you maybe move the non-unit16 versions out of the main folder (or delete them).

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/2157566/55969712-92cc2d80-5c7e-11e9-96c2-f20b15915380.png">

**Comment by constantinpape** [comment]
Looks great.

> Can you maybe move the non-unit16 versions out of the main folder (or delete them).

I will check with everyone who might be needing this and then remove it.

**Comment by tischi** [comment]
...and I don't know how much work it is, but could you (for the cells) choose as the anchor pixel a pixel that actually occurs within the objects (rather than the com, which can be sometimes outside the object)?

**Comment by constantinpape** [comment]
I can do this eventually by computing (eccentricity centers)[https://ukoethe.github.io/vigra/doc-release/vigranumpy/index.html#vigra.filters.eccentricityCenters] on a downscaled version of the segmentation.
But only for the final segmentation, because this will take quite  a while.

**Comment by constantinpape** [comment]
This is all implemented already.
