### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by tischi** [platybrowser/mmb-fiji#58]
@vzinche @K-Meech @HernandoMV 

I started writing a README section, to which we will refer to from our publication: https://github.com/platybrowser/platybrowser-fiji/blob/master/README.md

If you find some time, could you please check it and suggest additions?

**Comment by K-Meech** [comment]
Looks great to me! Very clear / easy to understand. 
It might be worth adding a 'Navigation' section or similar to give the basics of navigation in the main bigdataviewer window (e.g. scroll to zoom, middle click to pan etc.) The info is in the bigdataviewer help but it's a bit buried for a new user. 
Also, it would be worth explaining the main buttons on the bar for each selected item (e.g. C / B / X...) - maybe show a screenshot and then go through each option and what they do? 
For the options in the menu bar for the table, it would be good to describe the more complex ones like colour by column / annotations (I guess this could go in a separate file if you didn't want the readme to become too long?)

**Comment by vzinche** [comment]
Agree with Kimberly that table functions need more description. I think it's worth mentioning 'Append Table', 'Color by Column', 'Annotate' and especially 'Measure' (I didn't even know it exists :)

**Comment by tischi** [comment]
> and especially 'Measure'

@vzinche 
Does it even work? I started at some point implementing it, but I am not sure it is ready to be released...

**Comment by tischi** [comment]
@K-Meech 

Thanks a lot. I refactored your suggestions to make the off-tickable 😃 

- [ ] It might be worth adding a 'Navigation' section or similar to give the basics of navigation in the main bigdataviewer window (e.g. scroll to zoom, middle click to pan etc.) The info is in the bigdataviewer help but it's a bit buried for a new user.
- [ ] Also, it would be worth explaining the main buttons on the bar for each selected item (e.g. C / B / X...) maybe show a screenshot and then go through each option and what they do?
- [ ] table: colour by column 
- [ ] table: annotations (I guess this could go in a separate file if you didn't want the readme to become too long?)
- [ ] table: append

**Comment by vzinche** [comment]
> Does it even work? I started at some point implementing it, but I am not sure it is ready to be released...

I tried, it even gave me out a new distance column, but also threw an error:
![Screenshot from 2020-02-11 16-14-29](https://user-images.githubusercontent.com/32451366/74249678-d56cf500-4ce9-11ea-8d2e-ce0eac80e399.png)

**Comment by tischi** [comment]
- [ ] Remove measurements from table

**Comment by constantinpape** [comment]
@tischi two of the images in the Readme are out of data with the new UI:

- [ ] version 0.6.6 was renamed to 1.0.0
- [ ] the main UI window has changed ("show objects in 3d" is gone etc.)

**Comment by constantinpape** [comment]
@tischi I forgot one more thing:
The first image also needs to be updated because we renamed it from `Open PlatyBrowser` to just `PlatyBrowser`.
