### ISSUE TITLE
Improved handling of RGB images

### ISSUE THREAD

**Issue by CamachoDejay** [platybrowser/mmb-fiji#668]
Hi,

I understand that MoBIE is made to handle images as single channel images. This makes sense for most applications  However, for some applications, like H&E stain, polarization microscopy and other chromohpores, we need to handle colour (RGB) images. Do you have a plan in the future to handle RGB images in a different way? I am ok with loading each image’s channels c0 c1 c2, however this makes the list of “views” very large, when they could be “lock” together. Also it would be more convenient that all colour channels are looked in their contrast limits, so the colour balance is preserved.

Happy to give more info if needed.

Best,
Rafa

**Comment by constantinpape** [comment]
I think that the easiest way to do this is to use a view that combines the 3 images and sets the colors and opacity correctly.
You can then save this view back to the project and load it again to recreate it.
Would this work for you?

For how to do this from Fiji @K-Meech can probably describe this best; I am happy to show how to do it from python if that would help you ;).

**Comment by tischi** [comment]
> For how to do this from Fiji

Right click: `Save current view`

**Comment by K-Meech** [comment]
Yes - you'd just need to add those 3 images to the viewer, and set the opacity etc as you like then right click > Save Current View. You can save it directly to the project 'dataset.json' or to a separate file on your filesystem.

**Comment by CamachoDejay** [comment]
Hej,
Yes, I agree with you both that I can already make MoBIE work, and deliver what I want. My only issues as a user are:
1) I already know before hand that these are RGB images. I know I should load the 3 channles, and they should have same display limits.  It would be cool if the MoBIE project creator could understand this and handle it as such, even perhaps creating the view you are suggesting. 
2) in the case of multiple RGB images, then the amount of data/views grow fast:
![image](https://user-images.githubusercontent.com/4221906/162186519-f5dd4607-417b-49bb-a225-d99b3b0c1102.png)
3) it is a bit of work to manually create the view for each slide:
![image](https://user-images.githubusercontent.com/4221906/162186745-14f2d16f-cd0d-41d0-a835-ea4166d8b11c.png)

I know I am probably lazy but it feels to me that as a user this could be handled more automatically in the loading stage.

**Comment by tischi** [comment]
> I know I am probably lazy but it feels to me that as a user this could be handled more automatically in the loading stage.

@K-Meech Can we create views using the ProjectCreator API? If not, I think we should add it :-)

**Comment by K-Meech** [comment]
At the moment, it's not possible to make views through the API - but I agree it would be nice to add! Can you make a separate issue for this? I might have time to look into this next week maybe.

**Comment by CamachoDejay** [comment]
Sure that sounds like a good strategy. I will close this issue and add a link to it when opening one for views via the API
