### ISSUE TITLE
Show objects from different segmentations in same 3d viewer?

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/mmb-fiji#67]
Right now, objects from different segmentations are shown in different 3d viewer windows:

![Screenshot from 2020-02-19 15-31-32](https://user-images.githubusercontent.com/4263537/74844061-2ce41400-532d-11ea-8c82-f76c4dce9786.png)

For many use cases, we would rather have them in the same 3d viewer; e.g. for exploring different segmented ultra-structure objects and their interaction.
But there might also be use cases where separate viewers are better, so maybe we should support both?

**Comment by tischi** [comment]
They used to be show in the same viewer.
I can try to fix this....

**Comment by tischi** [comment]
done.
