### ISSUE TITLE
Buttons for showing objects/volumes in 3d viewer are confusing

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/mmb-fiji#70]
I think the functionality for showing 3d volumes/objects is distributed over too many buttons in the gui:
There are the general buttons `show objects in 3d`, `show volumes in 3d` + each layer has the button `V`. It is unclear how these interact which each other.

I would vote for getting rid of `show objects in 3d` and `show volumes in 3d` and just keeping the `V` button, that shows the volume in 3d for image/mask data and objects for segmentation data.

In additon, the naming of `V` and `B` is a bit sub-optimal. What does `B` stand for?

**Comment by tischi** [comment]
I agree and I'll try to implement your very good suggestion.

**Comment by tischi** [comment]
@constantinpape 
1. I did the changes, please test.
1. I replaced **B** by **S**, for Slice view. (B was for BDV)

Tomorrow I am the whole day in an ALMF retreat/meeting and will not have time to respond to anything.
Tuesday morning I can have a look again.
@HernandoMV The main UI slightly changed: the two 3D checkboxes are gone. It would be nice if you could change the figure in the paper.

**Comment by constantinpape** [comment]
I tested the changes; it is exactly how I think this should work now :).
I ran into another issue with 3d rendering now, see #71, but that is not really UI related.
Closing this issue for now, feel free to reopen if there are other UI related things.
