### ISSUE TITLE
Loading table with bookmarks appends 'label_id' as well

### ISSUE THREAD

**Issue by vzinche** [platybrowser/mmb-fiji#72]
When you run a bookmark that appends a table (e.g., symmetric cells) it appends the unnecessary 'label_id' column, that is not the case when you just append the table manually.
![Screenshot from 2020-02-24 11-29-45](https://user-images.githubusercontent.com/32451366/75145356-13f6ac80-56f9-11ea-8eba-1b6301088af6.png)

**Comment by tischi** [comment]
should be fixed. please try again tomorrow.

**Comment by vzinche** [comment]
Works, thanks!
