### ISSUE TITLE
Bookmark "Symmetric cell pairs" the table can't be loaded

### ISSUE THREAD

**Issue by vzinche** [platybrowser/mmb-fiji#73]
Did you push these changes? Because for me it still throws an error:

![Screenshot from 2020-02-19 09-55-08](https://user-images.githubusercontent.com/32451366/74817932-0bb7ff00-52fe-11ea-8508-7c6d9e44bb89.png)

**Comment by tischi** [comment]
Should be fixed. Please try again tomorrow.

**Comment by vzinche** [comment]
Fixed, thanks!
