### ISSUE TITLE
Cannot select github as image data source in CustomBrowser

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/mmb-fiji#75]
I run into a pretty bizarre issue when I try to open a `CustomBrowser` with a github backend for the image data:

1.) select the remote source for images and table
![Screenshot from 2020-02-28 19-59-24](https://user-images.githubusercontent.com/4263537/75578813-dc736180-5a64-11ea-9f13-9d139c16b776.png)

2.) select version (looks fine until know)
![Screenshot from 2020-02-28 20-00-30](https://user-images.githubusercontent.com/4263537/75578903-07f64c00-5a65-11ea-82b2-e90c15a2c3ed.png)

3.) exceptions after clicking ok
![Screenshot from 2020-02-28 19-55-23](https://user-images.githubusercontent.com/4263537/75578926-16446800-5a65-11ea-9409-040b4d445b46.png)

4.) check the addresses stored in `CustomBrowser`
![Screenshot from 2020-02-28 19-54-14](https://user-images.githubusercontent.com/4263537/75578985-28bea180-5a65-11ea-8aa6-3dd1ce78b06f.png)

Somehow the address was changed to `/home/pape/...` for the Image Data Location. Table Data Location is fine.

**Comment by constantinpape** [comment]
It looks a bit like something is trying to normalize the address as a local file system path; note that also the `//` after https is turned into `/`.

**Comment by constantinpape** [comment]
I think this is the offending line:
https://github.com/platybrowser/mmb-fiji/blob/7a19b24fb5a68c82a9db516da7b5175822fb3a67/src/main/java/de/embl/cba/platynereis/platybrowser/command/PlatyBrowserOpenAdvancedCommand.java#L17
The address should not be a `File`, but a `String` in order to allow for web addresses.

**Comment by tischi** [comment]
I changed it. Can you update and try?

**Comment by constantinpape** [comment]
> I changed it. Can you update and try?

Works now!
