### ISSUE TITLE
set BDV to interpolate when loading

### ISSUE THREAD

**Issue by martinschorb** [platybrowser/mmb-fiji#762]
Hi,

when showing multiple alpha-Blend sources (CLEM project), the black boundaries around the sources are visible. Those disappear when activating the "interpolate" mode.

Can this set to be active by default when MoBIE opens a BDV window?

**Comment by tischi** [comment]
> when showing multiple alpha-Blend sources (CLEM project), the black boundaries around the sources are visible. Those disappear when activating the "interpolate" mode.

This may be a coincide for your setup (monitor, BDV size, ...). For me the black boundaries are visible with and without interpolation (although to a different extend).
