### ISSUE TITLE
Separate BDV for segmentation objects

### ISSUE THREAD

**Issue by vzinche** [platybrowser/mmb-fiji#77]
Not sure whether this is a bug or a feature, but if one manages to add segmentation before the main BDV window is loaded, it just opens a separate window for the segmentation: 
![two_bdvs](https://user-images.githubusercontent.com/32451366/75782274-f6f85400-5d5e-11ea-8f97-32933116441b.gif)

**Comment by constantinpape** [comment]
I have seen this happen too. I guess the `add` functionality should be locked until the bdv window opens.

**Comment by tischi** [comment]
This is a bug. 
Thanks for finding and reporting it!
I fixed it.
