### ISSUE TITLE
Don't hard code the leveled view to the platy values.

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/mmb-fiji#88]
Leveled view is hard-coded to what's used for platy.
We should make this customizable too.

I would just add a bookmark called `leveled` to `bookmarks/default.json`.

**Comment by constantinpape** [comment]
Ok, @tisci had a better idea here: https://github.com/platybrowser/platybrowser/issues/53.
We will add a `leveling.json` to the misc folder. (And if it's not there, we should default to the image plane when leveling)

**Comment by tischi** [comment]
ok. i'll close this one then.
